[Eth]
NetworkId = 8453
SyncMode = "snap"

[Node]
DataDir = "/var/lib/base/geth"
HTTPHost = "0.0.0.0"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["eth", "net", "web3", "debug", "txpool"]
HTTPCors = ["*"]
WSHost = "0.0.0.0"
WSPort = 8546
WSOrigins = ["*"]
WSModules = ["eth", "net", "web3"]
AuthAddr = "0.0.0.0"
AuthPort = 8551
AuthVirtualHosts = ["*"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
ListenAddr = ":30303"
BootstrapNodes = []

[Metrics]
Enabled = true
HTTP = "0.0.0.0"
Port = 6060
